product-name: p-cloudcache
product-properties:
  .properties.authenticate_with_uaa:
    selected_option: disable
    value: disable
  .properties.canary_selection_params:
    selected_option: disable
    value: disable
  .properties.confirm_tls_setup:
    value: X
  .properties.default_distributed_system_id:
    value: 0
  .properties.dev_plan_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.dev_plan_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.dev_plan_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.dev_plan_enable_service_plan.enable.plan_name:
    value: dev-plan
  .properties.dev_plan_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.dev_plan_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.dev_plan_enable_service_plan.enable.service_metrics:
    value: true
  .properties.enable_secure_binding:
    value: true
  .properties.errand_plan:
    selected_option: plan1
    value: plan1
  .properties.number_simultaneous_upgrades:
    value: 1
  .properties.number_upgrade_canary_instances:
    value: 0
  .properties.plan1_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.plan1_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.plan1_enable_service_plan.enable.default_num_servers:
    value: 4
  .properties.plan1_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.plan1_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.plan1_enable_service_plan.enable.plan_name:
    value: extra-small
  .properties.plan1_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.plan1_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.plan1_enable_service_plan.enable.service_metrics:
    value: true
  .properties.plan2_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.plan2_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.plan2_enable_service_plan.enable.default_num_servers:
    value: 4
  .properties.plan2_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.plan2_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.plan2_enable_service_plan.enable.plan_name:
    value: small
  .properties.plan2_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.plan2_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.plan2_enable_service_plan.enable.service_metrics:
    value: true
  .properties.plan3_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.plan3_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.plan3_enable_service_plan.enable.default_num_servers:
    value: 4
  .properties.plan3_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.plan3_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.plan3_enable_service_plan.enable.plan_name:
    value: medium
  .properties.plan3_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.plan3_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.plan3_enable_service_plan.enable.service_metrics:
    value: true
  .properties.plan4_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.plan4_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.plan4_enable_service_plan.enable.default_num_servers:
    value: 4
  .properties.plan4_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.plan4_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.plan4_enable_service_plan.enable.plan_name:
    value: large
  .properties.plan4_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.plan4_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.plan4_enable_service_plan.enable.service_metrics:
    value: true
  .properties.plan5_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.plan5_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.plan5_enable_service_plan.enable.default_num_servers:
    value: 4
  .properties.plan5_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.plan5_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.plan5_enable_service_plan.enable.plan_name:
    value: extra-large
  .properties.plan5_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.plan5_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.plan5_enable_service_plan.enable.service_metrics:
    value: true
  .properties.settings_shareable_instances:
    selected_option: enabled
    value: "Yes"
  .properties.small_footprint_enable_service_plan:
    selected_option: enable
    value: enable
  .properties.small_footprint_enable_service_plan.enable.cf_service_access:
    value: enable
  .properties.small_footprint_enable_service_plan.enable.max_servers_per_cluster:
    value: 32
  .properties.small_footprint_enable_service_plan.enable.plan_description:
    value: Plan Description
  .properties.small_footprint_enable_service_plan.enable.plan_name:
    value: small-footprint
  .properties.small_footprint_enable_service_plan.enable.service_instance_azs:
    value:
    - Availability Sets
  .properties.small_footprint_enable_service_plan.enable.service_instance_quota:
    value: 10
  .properties.small_footprint_enable_service_plan.enable.service_metrics:
    value: true
  .properties.syslog:
    selected_option: enable
    value: enable
  .properties.syslog.enable.syslog_address:
    value: {{.syslog_host}}
  .properties.syslog.enable.syslog_enabled_for_service_instances:
    value: true
  .properties.syslog.enable.syslog_port:
    value: {{.syslog_port}}
  .properties.syslog.enable.syslog_protocol:
    value: udp
  .properties.syslog.enable.syslog_tls:
    value: false
  .properties.uaa_custom_url:
    selected_option: disable
    value: disable
network-properties:
  network:
    name: {{.services_subnet_name}}
  other_availability_zones:
  - name: Availability Sets
  service_network:
    name: {{.services_subnet_name}}
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  cloudcache-broker:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
    internet_connected: false
errand-config:
  delete-all-service-instances-and-deregister-broker:
    pre-delete-state: true
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true

