product-name: cf
network-properties:
  network:
    name: {{.pas_subnet_name}}
  other_availability_zones:
  - name: 'null'
  singleton_availability_zone:
    name: 'null'

product-properties:
  .properties.system_blobstore.external_azure.enable_bbr:
    value: true
  .properties.system_blobstore.external_azure.environment:
    value: AzureCloud
  .properties.smtp_address:
    value: {{.smtp_address}}
  .properties.smtp_auth_mechanism:
    value: none
  .properties.smtp_enable_starttls_auto:
    value: true
  .properties.smtp_from:
    value: {{.smtp_from}}
  .properties.smtp_port:
    value: 25
  .properties.syslog_agent_enabled:
    value: false
  .properties.syslog_drop_debug:
    value: true
  .properties.syslog_host:
    value: {{.syslog_host}}
  .properties.syslog_metrics_to_syslog_enabled:
    value: true
  .properties.syslog_port:
    value: {{.syslog_port}}
  .properties.syslog_protocol:
    value: udp
  .properties.syslog_tls:
    selected_option: disabled
    value: disabled
  .properties.syslog_use_tcp_for_file_forwarding_local_transport:
    value: false
  .properties.silk_database_max_open_connections:
    value: 200
  .properties.router_prune_all_stale_routes:
    value: false
  .properties.router_balancing_algorithm:
    selected_option: round_robin
    value: round-robin
  .properties.route_services.enable.internal_lookup:
    value: false
  .properties.push_apps_manager_app_poll_interval:
    value: 10
  .properties.networkpolicyserver_database_max_open_connections:
    value: 200
  .properties.networkpolicyserverinternal_database_max_open_connections:
    value: 200
  .properties.istio:
    selected_option: disable
    value: disable
  .properties.locket_database_max_open_connections:
    value: 200
  .properties.log_cache_max_per_source:
    value: 100000
  .properties.metric_registrar_blacklisted_tags:
    value: deployment,job,index,id
  .properties.metric_registrar_enabled:
    value: true
  .properties.metric_registrar_scrape_interval_in_seconds:
    value: 35
  .properties.garden_disk_cleanup.reserved.reserved_space_for_other_jobs_in_mb:
    value: 15360
  .properties.experimental_dynamic_egress_enforcement:
    value: false
  .properties.enable_garden_containerd_mode:
    value: true
  .properties.credhub_database:
    selected_option: internal_mysql
    value: internal_mysql
  .properties.container_networking_interface_plugin.silk.enable_policy_enforcement:
    value: true
  .properties.cloud_controller_temporary_disable_deployments:
    value: false
  .properties.cloud_controller_completed_tasks_cutoff_age_in_days:
    value: 31
  .properties.cf_networking_internal_domain:
    value: apps.internal
  .properties.autoscale_enable_notifications:
    value: true
  .mysql_proxy.enable_inactive_mysql_port:
    value: false
  .mysql.max_connections:
    value: 3500
  .properties.autoscale_enable_notifications:
    value: true
  .mysql_proxy.enable_inactive_mysql_port:
    value: false
  .properties.system_metrics_enabled:
    value: false
  .properties.uaa:
    selected_option: saml
    value: saml
  .properties.uaa.saml.display_name:
    value: {{.saml_display_name}}
  .properties.uaa.saml.email_attribute:
    value: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
  .properties.uaa.saml.email_domains:
    value: domain.com
  .properties.uaa.saml.external_groups_attribute:
    value: http://schemas.microsoft.com/ws/2008/06/identity/claims/groups
  .properties.uaa.saml.first_name_attribute:
    value: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
  .properties.uaa.saml.last_name_attribute:
    value: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
  .properties.uaa.saml.name_id_format:
    value: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
  .properties.uaa.saml.require_signed_assertions:
    value: false
  .properties.uaa.saml.sign_auth_requests:
    value: true
  .properties.uaa.saml.sso_name:
    value: azure
  .properties.uaa.saml.sso_url:
    value: {{.pas_saml_sso_url}}
  .cloud_controller.allow_app_ssh_access:
    value: true
  .cloud_controller.apps_domain:
    value: {{.apps_domain}}
  .cloud_controller.system_domain:
    value: {{.sys_domain}}
  .properties.cf_networking_search_domains:
    value: apps.internal
  .cloud_controller.default_app_memory:
    value: 512
  .cloud_controller.default_app_ssh_access:
    value: true
  .cloud_controller.default_disk_quota_app:
    value: 512
  .cloud_controller.default_quota_max_number_services:
    value: 100
  .cloud_controller.default_quota_memory_limit_mb:
    value: 10240
  .cloud_controller.enable_custom_buildpacks:
    value: true
  .cloud_controller.encrypt_key:
    value: {}
  .cloud_controller.max_disk_quota_app:
    value: 2048
  .cloud_controller.max_file_size:
    value: 1024
  .cloud_controller.security_event_logging_enabled:
    value: true
  .cloud_controller.staging_timeout_in_seconds:
    value: 900
  .diego_brain.starting_container_count_maximum:
    value: 200
  .ha_proxy.skip_cert_verify:
    value: true
  .mysql.cli_history:
    value: true
  .mysql.prevent_node_auto_rejoin:
    value: false
  .mysql.remote_admin_access:
    value: false
  .mysql_monitor.poll_frequency:
    value: 30
  .mysql_monitor.recipient_email:
    value: {{.recipient_email}}
  .mysql_monitor.write_read_delay:
    value: 20
  .mysql_proxy.shutdown_delay:
    value: 30
  .mysql_proxy.startup_delay:
    value: 0
  .nfs_server.blobstore_internal_access_rules:
    value: allow 10.0.0.0/8;,allow 172.16.0.0/12;,allow 192.168.0.0/16;
  .properties.autoscale_api_disable_connection_pooling:
    value: false
  .properties.autoscale_api_instance_count:
    value: 1
  .properties.autoscale_enable_verbose_logging:
    value: false
  .properties.autoscale_instance_count:
    value: 3
  .properties.autoscale_metric_bucket_count:
    value: 120
  .properties.autoscale_scaling_interval_in_seconds:
    value: 35
  .properties.cc_api_rate_limit:
    value: disable
  .properties.cc_logging_level:
    value: info
  .properties.ccdb_connection_validation_timeout:
    value: 3600
  .properties.ccdb_read_timeout:
    value: 3600
  .properties.cf_networking_database_connection_timeout:
    value: 120
  .properties.cf_networking_enable_space_developer_self_service:
    value: true
  .properties.cloud_controller_default_health_check_timeout:
    value: 60
  .properties.container_networking:
    value: disable
  .properties.container_networking_interface_plugin:
    value: silk
  .properties.container_networking_interface_plugin.silk.enable_log_traffic:
    value: false
  .properties.container_networking_interface_plugin.silk.iptables_accepted_udp_logs_per_sec:
    value: 100
  .properties.container_networking_interface_plugin.silk.iptables_denied_logs_per_sec:
    value: 1
  .properties.container_networking_interface_plugin.silk.network_mtu:
    value: 1454
  .properties.container_networking_interface_plugin.silk.vtep_port:
    value: 4789
  .properties.credhub_key_encryption_passwords:
    value:
    - key:
        secret: {{.credhub_encrypt_key}}
      name: Key
      primary: true
      provider: internal
  .properties.diego_log_timestamp_format:
    value: unix-epoch
  .properties.garden_disk_cleanup:
    selected_option: reserved
    value: reserved
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
  .properties.haproxy_client_cert_validation:
    value: none
  .properties.haproxy_forward_tls:
    value: disable
  .properties.haproxy_hsts_support:
    value: disable
  .properties.haproxy_max_buffer_size:
    value: 16384
  .properties.haproxy_ssl_ciphers:
    value: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384
  .properties.mysql_activity_logging:
    value: enable
  .properties.mysql_activity_logging.enable.audit_logging_events:
    value: connect,query
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
{{indent 10 .ssl_cert}}
        private_key_pem: |
{{indent 10 .ssl_private_key}}
      name: Certificate
  .properties.nfs_volume_driver:
    value: enable
  .properties.nfs_volume_driver.enable.ldap_service_account_password:
    value: {}
  .properties.push_apps_manager_accent_color:
    value: '#FF6600'
  .properties.push_apps_manager_company_name:
    value: company_name
  .properties.push_apps_manager_currency_lookup:
    value: '{ "usd": "$", "eur": "€" }'
  .properties.push_apps_manager_display_plan_prices:
    value: false
  .properties.push_apps_manager_enable_invitations:
    value: true
  .properties.push_apps_manager_favicon:
    value: {{.push_apps_manager_favicon}}
  .properties.push_apps_manager_footer_text:
    value: {{.push_apps_manager_footer_text}}
  .properties.push_apps_manager_global_wrapper_bg_color:
    value: '#333333'
  .properties.push_apps_manager_global_wrapper_text_color:
    value: '#ff6600'
  .properties.push_apps_manager_logo:
    value: {{.push_apps_manager_logo}}
  .properties.push_apps_manager_poll_interval:
    value: 30
  .properties.push_apps_manager_square_logo:
    value: {{.push_apps_manager_square_logo}}
  .properties.route_services:
    value: enable
  .properties.route_services.enable.ignore_ssl_cert_verification:
    value: true
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_client_cert_validation:
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    value: enable
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    value: log_client_ips
  .properties.routing_minimum_tls_version:
    value: tls_v1_2
  .properties.routing_tls_termination:
    value: load_balancer
  .properties.saml_signature_algorithm:
    value: SHA256
  .properties.secure_service_instance_credentials:
    value: true
  .properties.security_acknowledgement:
    value: X
  .properties.smoke_tests:
    value: on_demand
  .properties.system_blobstore:
    value: external_azure
  .properties.system_blobstore.external_azure.access_key:
    value:
      secret: {{.cf_storage_account_access_key}}
  .properties.system_blobstore.external_azure.account_name:
    value: {{.cf_storage_account_name}}
  .properties.system_blobstore.external_azure.buildpacks_container:
    value: {{.cf_buildpacks_storage_container}}
  .properties.system_blobstore.external_azure.droplets_container:
    value: {{.cf_droplets_storage_container}}
  .properties.system_blobstore.external_azure.packages_container:
    value: {{.cf_packages_storage_container}}
  .properties.system_blobstore.external_azure.resources_container:
    value: {{.cf_resources_storage_container}}
  .properties.system_blobstore_ccdroplet_max_staged_droplets_stored:
    value: 2
  .properties.system_blobstore_ccpackage_max_valid_packages_stored:
    value: 2
  .properties.system_database:
    selected_option: internal_pxc
    value: internal_pxc
  .properties.uaa_database:
    selected_option: internal_mysql
    value: internal_mysql
  .properties.uaa_session_cookie_max_age:
    value: 28800
  .properties.uaa_session_idle_timeout:
    value: 1800
  .router.disable_insecure_cookies:
    value: false
  .router.drain_wait:
    value: 20
  .router.enable_isolated_routing:
    value: false
  .router.enable_write_access_logs:
    value: true
  .router.enable_zipkin:
    value: true
  .router.frontend_idle_timeout:
    value: 900
  .router.lb_healthy_threshold:
    value: 20
  .router.request_timeout_in_seconds:
    value: 900
  .uaa.apps_manager_access_token_lifetime:
    value: 1209600
  .uaa.cf_cli_access_token_lifetime:
    value: 7200
  .uaa.cf_cli_refresh_token_lifetime:
    value: 1209600
  .uaa.customize_password_label:
    value: Password
  .uaa.customize_username_label:
    value: ID
  .uaa.proxy_ips_regex:
    value: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}
  .properties.tcp_routing:
    selected_option: enable
    value: enable
  .properties.tcp_routing.enable.reservable_ports:
    value: 1024-1123
  .uaa.service_provider_key_credentials:
    value:
        cert_pem: |
{{indent 10 .ssl_cert}}
        private_key_pem: |
{{indent 10 .ssl_private_key}}
resource-config:
  diego_brain:
    elb_names:
    - {{.diego_ssh_lb_name}}
  router:
    elb_names:
    - {{.web_lb_name}}
    instances: automatic
  tcp_router:
    elb_names:
    - {{.tcp_lb_name}}
  mysql_proxy:
    elb_names:
    - {{.mysql_lb_name}}
    instances: automatic
  ha_proxy:
    instances: 0
    instance_type:
      id: automatic
  nats:
    instances: automatic
    instance_type:
      id: automatic
  syslog_adapter:
    instances: automatic
    instance_type:
      id: automatic
  syslog_scheduler:
    instances: automatic
    instance_type:
      id: automatic
  credhub:
    instances: 2
    instance_type:
      id: automatic
  diego_cell:
    instance_type:
      id: automatic
    instances: 8

errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: true
  deploy-notifications-ui:
    post-deploy-state: true
  nfsbrokerpush:
    post-deploy-state: true
  push-apps-manager:
    post-deploy-state: true
  push-usage-service:
    post-deploy-state: true
  smoke_tests:
    post-deploy-state: true
  test-autoscaling:
    post-deploy-state: true
